### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by vishalforu** [yadunandankushwaha/CodeIgniter-3.1.5-complete-project-with-frontend-admin#3]
Dear your code is well good, but i have faced some issues in it. Pagination is one of them. On listing pages pagination is not working so if you have solution for it then please share it.

Thank You!

**Comment by allamiro** [comment]
Do you know which one? post screenshot may be ! I have looked the codeigniter reference and I realized if you able to get the installation working you can use this as a reference to update the pagination on that page

[https://codeigniter.com/user_guide/libraries/pagination.html](https://codeigniter.com/user_guide/libraries/pagination.html
)

**Comment by yadunandankushwaha** [comment]
Resolved!
