### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ph4t0o0o0om** [yadunandankushwaha/CodeIgniter-3.1.5-complete-project-with-frontend-admin#4]
Thank you for a very good template.

But I encounter some errors the links on homepage is missing when I
click the link on header
like (Home,About.Blog,Catergory) it redirects me to the broken link.

Can you help me for this one?

**Comment by allamiro** [comment]
you will have to update the config.php  to your link url 
But i think there are also other links that are broken 

`$config['base_url'] = 'http://localhost/projectfolder/';`

**Comment by allamiro** [comment]
The documentation might need a little update with screenshots on how to configure it  as it doesn't work straight from the box.
However its a great effort ..

**Comment by yadunandankushwaha** [comment]
Thankyou Allamiro

**Comment by yadunandankushwaha** [comment]
Yes, definitely I am planning to update this project soon.
